# SPDX-License-Identifier: BSD-2-Clause
#
# SPDX-FileCopyrightText: 2023 Kai Uwe Broulik <ghqalpha@broulik.de>

name: Documentation

on: ["push"]

jobs:
  doxygen:
    strategy:
      matrix:
        config:
        - {name: "Ubuntu 22.04 (GCC)", os: "ubuntu-22.04", CC: "gcc", CXX: "g++"}

    name: ${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}

    steps:
    - name: Install dependencies
      env:
        DEBIAN_FRONTEND: "noninteractive"
      run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Run Doxygen
      run: |
        doxygen

    - name: Publish Documentation
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: docs/html

# TODO
